<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Web Hosting - courtesy of www.bluehost.com_ad_frame</name>
   <tag></tag>
   <elementGuidId>07a46635-f0ba-4d0c-bcae-5c4c69c04ec6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ad_frame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ad_frame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>108ac8af-3d4c-4699-9523-d5ff8d941819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ad_frame</value>
      <webElementGuid>7ee8547a-62f2-4c22-93e7-9d0fd4070b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d2f52c0e-da48-48ab-ab91-8958585dde83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>800</value>
      <webElementGuid>b5f1f13a-e917-400d-9d40-cebe2e1d06ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>25f5783c-8c09-4b64-a0e3-efad4172ebbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>5b807e8f-a22d-4353-a422-ed7bc19bb082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://www.iyfubh.com/?dn=lifecharger.org&amp;pid=9POJB64QD</value>
      <webElementGuid>58de8074-c2fd-4ab6-8f05-1a1b168718fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ad_frame&quot;)</value>
      <webElementGuid>01a31d3a-acf0-46b3-a2e1-434f5852e1b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ad_frame']</value>
      <webElementGuid>647c8915-21a4-4e43-8f13-7f33f7138a03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>cebb0f21-271c-4dbf-800d-958ea722d91b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ad_frame' and @src = 'http://www.iyfubh.com/?dn=lifecharger.org&amp;pid=9POJB64QD']</value>
      <webElementGuid>6e95dbd0-46dc-4a0e-a52e-8f7677b894af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
